require:
  - rubocop-rspec
  - rubocop-performance

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 12

RSpec/MessageSpies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 14

Metrics/AbcSize:
  Max: 27

Metrics/ClassLength:
  Max: 130

Metrics/CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/'
    - '*.gemspec'
  TargetRubyVersion: 2.5.5
